### ISSUE TITLE
Project status ?

### ISSUE THREAD

**Issue by Manukineko** [matthewp/comic-reader#73]
Hello,
I just bump into your project while researching system to put a cbz/r reader for the website about my comic I plan to build, and I was like "I finally found it \o/", but it says to not be use in production and the last commit seems quite old.
Sooo I wanted it has been abandoned.

Thank you.

**Comment by matthewp** [comment]
Not abandoned. I'm actually planning spending more time on this project now.

Depending on your needs and expectations you might give it a try and use it on a website. Let me know if you do and I'll help with any problems you run into.
